version: "3.7"

services:
  player:
    build:
      context: ./player
      dockerfile: Dockerfile
    command: npm run serve
    ports:
      - "3000:3000"
    user: "1000"
    volumes:
      - ./player:/usr/src/app
      - ./passwd:/etc/passwd
      - home:/home/server
volumes:
  home:
