import { SnapshotOutOfModel } from "mobx-keystone";
import Session from "services/models/session";

const exampleOne: SnapshotOutOfModel<Session> = {
  name: "Demo #1 - Apex Legends Match",
  selectedVideoRef: {
    id: "62f0f61d-fda9-41e1-9c61-69c65d0ff6d3",
    $modelType: "VodonPlayer/VideoRef",
  },
  createdAt: 1676973946345,
  videos: [
    {
      name: "Etro",
      type: "video/mp4",
      videoData: {
        $frozen: true,
        data: {
          "@type": "Video",
          StreamOrder: "0",
          ID: "1",
          Format: "AVC",
          Format_Profile: "High",
          Format_Level: "5",
          Format_Settings_CABAC: "No",
          Format_Settings_RefFrames: "16",
          CodecID: "avc1",
          Duration: "100.934",
          BitRate: "13963187",
          Width: "1280",
          Height: "720",
          Sampled_Width: "1280",
          Sampled_Height: "720",
          PixelAspectRatio: "1.000",
          DisplayAspectRatio: "1.778",
          Rotation: "0.000",
          FrameRate_Mode: "CFR",
          FrameRate_Mode_Original: "VFR",
          FrameRate: "30.000",
          FrameCount: "3028",
          ColorSpace: "YUV",
          ChromaSubsampling: "4:2:0",
          BitDepth: "8",
          ScanType: "Progressive",
          StreamSize: "176168873",
          Encoded_Library: "x264 - core 155 r2917 0a84d98",
          Encoded_Library_Name: "x264",
          Encoded_Library_Version: "core 155 r2917 0a84d98",
          Encoded_Library_Settings:
            "cabac=0 / ref=16 / deblock=0:0:0 / analyse=0x3:0x133 / me=umh / subme=10 / psy=1 / psy_rd=1.00:0.00 / mixed_ref=1 / me_range=24 / chroma_me=1 / trellis=2 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-2 / threads=22 / lookahead_threads=3 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=8 / b_pyramid=2 / b_adapt=2 / b_bias=0 / direct=3 / weightb=0 / open_gop=0 / weightp=0 / keyint=250 / keyint_min=25 / scenecut=40 / intra_refresh=0 / rc_lookahead=60 / rc=crf / mbtree=1 / crf=18.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / ip_ratio=1.40 / aq=1:1.00",
          extra: { CodecConfigurationBox: "avcC" },
        },
      },
      url: "https://vodon-random-hosting.sgp1.cdn.digitaloceanspaces.com/vodon-player%2Fdemo%2Fetro_720_faststart.mp4",
      bookmarks: [],
      createdAt: 1676974359763,
      copyToStorageInProgress: null,
      copyToStorageProgress: null,
      videoElementsCreated: true,
      offset: 38.433333,
      currentTime: 88.1,
      setupVideoPlaying: false,
      setupVideoSeeking: false,
      reviewVideoPlaying: false,
      reviewVideoSeeking: false,
      volume: 0.5,
      seenBookmarkIds: [],
      id: "62f0f61d-fda9-41e1-9c61-69c65d0ff6d3",
      $modelType: "VodonPlayer/Video",
    },
    {
      name: "Nanda",
      type: "video/mp4",
      videoData: {
        $frozen: true,
        data: {
          "@type": "Video",
          StreamOrder: "0",
          ID: "1",
          Format: "AVC",
          Format_Profile: "High",
          Format_Level: "5",
          Format_Settings_CABAC: "No",
          Format_Settings_RefFrames: "16",
          CodecID: "avc1",
          Duration: "90.450",
          BitRate: "17700552",
          Width: "1280",
          Height: "720",
          Sampled_Width: "1280",
          Sampled_Height: "720",
          PixelAspectRatio: "1.000",
          DisplayAspectRatio: "1.778",
          Rotation: "0.000",
          FrameRate_Mode: "CFR",
          FrameRate_Mode_Original: "VFR",
          FrameRate: "60.000",
          FrameCount: "5427",
          ColorSpace: "YUV",
          ChromaSubsampling: "4:2:0",
          BitDepth: "8",
          ScanType: "Progressive",
          StreamSize: "200126871",
          Title: "VideoHandle",
          Encoded_Library: "x264 - core 155 r2917 0a84d98",
          Encoded_Library_Name: "x264",
          Encoded_Library_Version: "core 155 r2917 0a84d98",
          Encoded_Library_Settings:
            "cabac=0 / ref=16 / deblock=0:0:0 / analyse=0x3:0x133 / me=umh / subme=10 / psy=1 / psy_rd=1.00:0.00 / mixed_ref=1 / me_range=24 / chroma_me=1 / trellis=2 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-2 / threads=22 / lookahead_threads=3 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=8 / b_pyramid=2 / b_adapt=2 / b_bias=0 / direct=3 / weightb=0 / open_gop=0 / weightp=0 / keyint=250 / keyint_min=25 / scenecut=40 / intra_refresh=0 / rc_lookahead=60 / rc=crf / mbtree=1 / crf=18.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / ip_ratio=1.40 / aq=1:1.00",
          extra: { CodecConfigurationBox: "avcC" },
        },
      },
      url: "https://vodon-random-hosting.sgp1.cdn.digitaloceanspaces.com/vodon-player%2Fdemo%2Fnanda_720_faststart.mp4",
      bookmarks: [],
      createdAt: 1676974359763,
      copyToStorageInProgress: null,
      copyToStorageProgress: null,
      videoElementsCreated: true,
      offset: 26.9,
      currentTime: 76.6,
      setupVideoPlaying: false,
      setupVideoSeeking: false,
      reviewVideoPlaying: false,
      reviewVideoSeeking: false,
      volume: 0.5,
      seenBookmarkIds: [],
      id: "ca98fcd0-8440-46ac-a70d-a19d07605144",
      $modelType: "VodonPlayer/Video",
    },
    {
      name: "Wolf",
      type: "video/mp4",
      videoData: {
        $frozen: true,
        data: {
          "@type": "Video",
          StreamOrder: "0",
          ID: "1",
          Format: "AVC",
          Format_Profile: "High",
          Format_Level: "5",
          Format_Settings_CABAC: "No",
          Format_Settings_RefFrames: "16",
          CodecID: "avc1",
          Duration: "180.017",
          BitRate: "14867013",
          Width: "1280",
          Height: "720",
          Sampled_Width: "1280",
          Sampled_Height: "720",
          PixelAspectRatio: "1.000",
          DisplayAspectRatio: "1.778",
          Rotation: "0.000",
          FrameRate_Mode: "CFR",
          FrameRate_Mode_Original: "VFR",
          FrameRate: "60.000",
          FrameCount: "10801",
          ColorSpace: "YUV",
          ChromaSubsampling: "4:2:0",
          BitDepth: "8",
          ScanType: "Progressive",
          StreamSize: "334538761",
          Encoded_Library: "x264 - core 155 r2917 0a84d98",
          Encoded_Library_Name: "x264",
          Encoded_Library_Version: "core 155 r2917 0a84d98",
          Encoded_Library_Settings:
            "cabac=0 / ref=16 / deblock=0:0:0 / analyse=0x3:0x133 / me=umh / subme=10 / psy=1 / psy_rd=1.00:0.00 / mixed_ref=1 / me_range=24 / chroma_me=1 / trellis=2 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-2 / threads=22 / lookahead_threads=3 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=8 / b_pyramid=2 / b_adapt=2 / b_bias=0 / direct=3 / weightb=0 / open_gop=0 / weightp=0 / keyint=250 / keyint_min=25 / scenecut=40 / intra_refresh=0 / rc_lookahead=60 / rc=crf / mbtree=1 / crf=18.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / ip_ratio=1.40 / aq=1:1.00",
          extra: { CodecConfigurationBox: "avcC" },
        },
      },
      url: "https://vodon-random-hosting.sgp1.cdn.digitaloceanspaces.com/vodon-player%2Fdemo%2Fwolf_720_faststart.mp4",
      bookmarks: [],
      createdAt: 1676974359763,
      copyToStorageInProgress: null,
      copyToStorageProgress: null,
      videoElementsCreated: true,
      offset: 116.016667,
      currentTime: 165.7,
      setupVideoPlaying: false,
      setupVideoSeeking: false,
      reviewVideoPlaying: false,
      reviewVideoSeeking: false,
      volume: 0.5,
      seenBookmarkIds: [],
      id: "9a1d5df1-a075-4213-ab80-c24a0c950a11",
      $modelType: "VodonPlayer/Video",
    },
  ],
  showReviewVideoPanel: true,
  showBookmarksPanel: true,
  id: "7333e9fe-10ec-4955-a2f7-66ebe9034cf2",
  $modelType: "VodonPlayer/Session",
};

export default exampleOne;
